apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-09-19T19:13:33Z"
  generateName: jenkins-695445b556-
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
    pod-template-hash: 695445b556
    run: jenkins
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:pod-template-hash: {}
          f:run: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"109d10a6-39c6-4c55-b482-19746610c180"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"jenkins"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":50000,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/var/jenkins_home"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"jenkinshome"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-19T19:13:33Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.13"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-09-19T19:14:09Z"
  name: jenkins-695445b556-k7c6w
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jenkins-695445b556
    uid: 109d10a6-39c6-4c55-b482-19746610c180
  resourceVersion: "96216"
  selfLink: /api/v1/namespaces/default/pods/jenkins-695445b556-k7c6w
  uid: d6597b50-ab70-4131-8b33-2da6bb7f15fb
spec:
  containers:
  - image: vskurikhin/aarch64-jenkins:v2.249.1.2
    imagePullPolicy: IfNotPresent
    name: jenkins
    ports:
    - containerPort: 8080
      name: web
      protocol: TCP
    - containerPort: 50000
      name: slaves
      protocol: TCP
    resources:
      limits:
        cpu: "4"
        memory: 3Gi
      requests:
        cpu: 50m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkinshome
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-v99nd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: rpi01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jenkinshome
    persistentVolumeClaim:
      claimName: jenkins
  - name: default-token-v99nd
    secret:
      defaultMode: 420
      secretName: default-token-v99nd
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-19T19:13:33Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-19T19:14:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-19T19:14:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-19T19:13:33Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://96c4f085b3ecb8bfe0d0f3b2102a5b30668d90b97a04f337e394cc03e09bd1a1
    image: vskurikhin/aarch64-jenkins:v2.249.1.2
    imageID: docker-pullable://vskurikhin/aarch64-jenkins@sha256:d02717f10bfc10355fa43a8a968fae0b901a408d8c82223ccd2a55816b56b530
    lastState: {}
    name: jenkins
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-19T19:14:08Z"
  hostIP: 192.168.21.41
  phase: Running
  podIP: 10.244.1.13
  podIPs:
  - ip: 10.244.1.13
  qosClass: Burstable
  startTime: "2020-09-19T19:13:33Z"
