apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-09-19T16:30:06Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: my
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.35.0
    helm.sh/chart: ingress-nginx-3.1.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-19T16:30:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalIPs: {}
    manager: kubectl-edit
    operation: Update
    time: "2020-09-19T18:24:35Z"
  name: my-ingress-nginx-controller
  namespace: default
  resourceVersion: "87369"
  selfLink: /api/v1/namespaces/default/services/my-ingress-nginx-controller
  uid: 5ce1d7d3-4de1-4bb9-aeec-a5de404d5bf6
spec:
  clusterIP: 10.98.91.150
  externalIPs:
  - 192.168.21.40
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30224
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30755
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: my
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
