apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /nfs/rpi/jenkins
    server: 192.168.21.39
