apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
