apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-19T18:39:07Z"
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
    run: jenkins
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:run: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2020-09-19T18:39:07Z"
  name: jenkins
  namespace: default
  resourceVersion: "89835"
  selfLink: /api/v1/namespaces/default/services/jenkins
  uid: 048e867e-1bb9-4ee6-b447-3ad6b3928250
spec:
  clusterIP: 10.108.10.99
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
    run: jenkins
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
