apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-09-19T16:30:05Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: my
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.35.0
    helm.sh/chart: ingress-nginx-3.1.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-19T16:30:05Z"
  name: my-ingress-nginx-controller
  namespace: default
  resourceVersion: "68714"
  selfLink: /api/v1/namespaces/default/configmaps/my-ingress-nginx-controller
  uid: 8dafcdd9-12e3-4b56-8cec-c7312e3e8f2f
