apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs-client-provisioner
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-09-19T18:08:31Z"
  generation: 1
  labels:
    app: nfs-client-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-client-provisioner-1.2.9
    heritage: Helm
    release: nfs-client-provisioner
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
            f:release: {}
        f:strategy:
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:release: {}
          f:spec:
            f:containers:
              k:{"name":"nfs-client-provisioner"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"NFS_PATH"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NFS_SERVER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PROVISIONER_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/persistentvolumes"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"nfs-client-root"}:
                .: {}
                f:name: {}
                f:nfs:
                  .: {}
                  f:path: {}
                  f:server: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-19T18:08:31Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-19T18:08:45Z"
  name: nfs-client-provisioner
  namespace: default
  resourceVersion: "84374"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nfs-client-provisioner
  uid: 4f08c330-d4d4-46aa-8bef-37b3f1e42a29
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-client-provisioner
        release: nfs-client-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-client-provisioner
        - name: NFS_SERVER
          value: 192.168.21.39
        - name: NFS_PATH
          value: /nfs/rpi
        image: quay.io/external_storage/nfs-client-provisioner-arm:v3.1.0-k8s1.11
        imagePullPolicy: IfNotPresent
        name: nfs-client-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-client-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-client-provisioner
      serviceAccountName: nfs-client-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-client-root
        nfs:
          path: /nfs/rpi
          server: 192.168.21.39
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-19T18:08:45Z"
    lastUpdateTime: "2020-09-19T18:08:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-19T18:08:31Z"
    lastUpdateTime: "2020-09-19T18:08:45Z"
    message: ReplicaSet "nfs-client-provisioner-544c5bb966" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
